events.md: add-new-events
3mdeb/3mdeb-website pull request #124
Opened 2024-03-04 11:10 UTC by Stanislaw-bnk

2024-03-04 11:39 UTC, artur-rs requested changes

2024-03-04 11:39 UTC, artur-rs commented on assets/images/events/2024/Yocto_Project_logo.svg.png
@Stanislaw-bnk I dont think that adding 2nd yocto image is necessary, or maybe there is a reason? See the previous file here: https://github.com/3mdeb/3mdeb-website/blob/main/content/markets.md?plain=1#L64

2024-03-04 11:39 UTC, artur-rs commented on content/events.md
> +    - title: "Xeon Project **Summit**"
@Stanislaw-bnk Xeon?

2024-03-04 11:44 UTC, Stanislaw-bnk commented on content/events.md
> +    - title: "Xeon Project **Summit**"
@artur-rs Thanx, fixed: 562c1a1d82428577858d9e40be535fbc9be2b0ac

2024-03-04 11:44 UTC, Stanislaw-bnk commented on assets/images/events/2024/Yocto_Project_logo.svg.png
Deleted: 562c1a1d82428577858d9e40be535fbc9be2b0ac

2024-03-04 11:51 UTC, artur-rs commented on assets/images/events/2024/Yocto_Project_logo.svg.png
@Stanislaw-bnk what it was added for? Shouldn't we change the yocto event image path to the old one?

2024-03-04 12:32 UTC, Stanislaw-bnk commented on assets/images/events/2024/Yocto_Project_logo.svg.png
@artur-rs I had to do a little research to understand why I added this logo in the first place. It seems that it was added for the 2023 Yocto Project at the Embedded Open-Source Summit event. It is of better quality than the logo that has already been added. So I've put it back: 483357d54cbae6c5c978f5e4024c42a5ab5c436d

2024-03-04 12:53 UTC, artur-rs commented on assets/images/events/2024/Yocto_Project_logo.svg.png
@Stanislaw-bnk Rather than adding 2nd image, you should replace the old one, keeping the same filename. But before that, you should confirm that the quality vs image size is acceptable by the SEO standards.

2024-03-06 12:49 UTC, Stanislaw-bnk commented on assets/images/events/2024/Yocto_Project_logo.svg.png
@artur-rs Not sure which one to replace as there are few yocto images in the assets: 
![Screenshot from 2024-03-06 13-48-41](https://github.com/3mdeb/3mdeb-website/assets/53895255/60de7b38-117c-4b0b-b44c-99c69f3bbc0a)
Will have to investigate that further, but we need the events page updated soon.

2024-03-06 12:57 UTC, artur-rs commented on assets/images/events/2024/Yocto_Project_logo.svg.png
@Stanislaw-bnk check what is currently used on the pages with the logo. So far I saw only one asset on this page: https://3mdeb.com/markets/ - so inspecting this file: https://github.com/3mdeb/3mdeb-website/blob/main/content/markets.md?plain=1#L64 shows that the we are using this file: `"images/used-technology/yocto.png"`. You can simply `grep` the repo for "Yocto" or similar text and check the output.

2024-03-06 18:08 UTC, Stanislaw-bnk commented on assets/images/events/2024/Yocto_Project_logo.svg.png
@artur-rs The logo was also used in a few different places on the website. I've changed it for the new logo which is better quality. I also tinified the .png size and scale the image. Now we have only 3 logos in the assets:
![Screenshot from 2024-03-06 19-08-24](https://github.com/3mdeb/3mdeb-website/assets/53895255/5c38f043-a96b-4e9d-a3a3-b4d69d7e0379)

2024-03-06 20:29 UTC, artur-rs commented on assets/images/events/2024/Yocto_Project_logo.svg.png
@Stanislaw-bnk after introducing above changes, please always check the localhost
* you used the wrong files for a registered logo (it should be Yocto participant one); new dimensions make it not aligned with other logos (main page, section `We are Registered` / `About Us` page)
* `embedded firmware development`, `Open Source Software`, `Open Source Hardware`, `Operating Systems`, `Training/YoctoProjectDevelopment` pages - it's larger than the rest of the technology logos, but I'll leave it to you if you want to change it back.. On `Open Source Hardware` it's definitely too large
* `markets` page - Yocto logo is deformed

2024-03-07 08:53 UTC, Stanislaw-bnk commented on assets/images/events/2024/Yocto_Project_logo.svg.png
@artur-rs Can we than delete this latest commit? 3f7a6f82b89c131a8af30d6695c68f9d75b5fe1c
It creates more problems than it solves.

2024-03-07 13:01 UTC, artur-rs commented on assets/images/events/2024/Yocto_Project_logo.svg.png
@Stanislaw-bnk removed

2024-03-07 19:05 UTC, Stanislaw-bnk commented on assets/images/events/2024/Yocto_Project_logo.svg.png
@artur-rs So in the end the yocto logo that was already in the assets was not in the best resolution for the events page. I've rescaled the logo specifically for events.

2024-03-07 19:23 UTC, artur-rs approved these changes

2024-03-07 19:23 UTC, merged