events: page-update
3mdeb/3mdeb-website pull request #130
Opened 2024-03-20 09:17 UTC by Stanislaw-bnk

2024-03-21 14:18 UTC, artur-rs requested changes

2024-03-21 14:18 UTC, artur-rs commented on content/events.md
> +      status: "upcoming"
@Stanislaw-bnk wrong status

2024-03-21 14:18 UTC, artur-rs commented on content/events.md
> +    - title: "Yocto Project **Dev Days**"
@Stanislaw-bnk shouldn't we leave the historical events' names?

2024-03-21 19:30 UTC, Stanislaw-bnk commented on content/events.md
> +    - title: "Yocto Project **Dev Days**"
This change is based on this comment: https://chat.3mdeb.com/team-3mdeb/pl/cnh6ktq38b8jujx3u4kppujfxw

2024-03-21 23:44 UTC, pietrushnic commented on content/events.md
> +    - title: "Yocto Project **Dev Days**"
@Stanislaw-bnk, this is a very bad idea to link private discussions from our company chat to a public repository; please remove that.

2024-03-22 09:05 UTC, artur-rs commented on content/events.md
> +    - title: "Yocto Project **Dev Days**"
Thanks for clarification

2024-03-22 09:06 UTC, artur-rs approved these changes

2024-03-22 09:06 UTC, merged