faq-shop: new-faq-section-for-shop
3mdeb/3mdeb-website pull request #132
Opened 2024-04-12 12:26 UTC by Stanislaw-bnk

2024-04-16 13:24 UTC, rafkoch requested changes

2024-04-16 13:24 UTC, rafkoch commented on content/faq-shop.md
> +Shipping costs are dependent on your location and products on your order. The
@Stanislaw-bnk  
od "location" czy może bardziej od adresu / kraju? 
Wiem, że to niby to samo, ale jak sobie przetestowałem w naszym sklepie to cenę wysyłki widzę dopiero po uzupełnieniu całego adresu, nawet bezsensownie jest zaznaczony suwak "Ship to a different address?"
i dopiero jak go wyłączyłem (bo nie chciałem podawać dodatkowego adresu) to wtedy wyświetlił się koszt wysyłki.
Może doszczegółowić to w podobny sposób, że by klient wiedział, że jak uzuepłni dane adresowe to zobaczy cenę finalną włącznie z wysyłką. 
Widzę, że napisałeś coś podobnego, jednak brakuje wzmianki, że chodzi o PEŁNE DANE ADRESOWE.

2024-04-16 13:24 UTC, rafkoch commented on content/faq-shop.md
> +<https://docs.dasharo.com/osf-trivia-list/dasharo/>
@Stanislaw-bnk link do FAQ Dasharo dodatkowo dałbym też w sekcji powyżej tj. "###### Q: I have some questions about the certain products in your store."

2024-04-16 13:24 UTC, rafkoch commented on content/faq-shop.md
> +<https://docs.dasharo.com/ways-you-can-help-us/>
@Stanislaw-bnk piszę w ostatniej linii FAQ, bo brakuje mi pytania i odp. dot. "skrupulatnego odbioru paczki". 
Przejrzyj solifnie opis zadania w JIRA i uzupełnij FAQ o pozycje tam odnotowane: [JIRA(https://jira-3mdeb.atlassian.net/browse/DEBSHOP-555)

2024-04-16 13:26 UTC, pietrushnic commented
@rafkoch This is a public repository. Please use English and do not provide links to private issue trackers.

2024-04-16 18:44 UTC, rafkoch commented
> @rafkoch This is a public repository. Please use English and do not provide links to private issue trackers.

@pietrushnic sorry, I translate my three comments from polish to english language and I remove link to private issue tracker.

2024-04-18 07:48 UTC, Stanislaw-bnk commented on content/faq-shop.md
> +<https://docs.dasharo.com/ways-you-can-help-us/>
@rafkoch I was intending to add it but did not do it previously. Anyway here it is: d296fad3cce66284ec1f8b1e8a5895cd2ffe515e

2024-04-19 07:53 UTC, rafkoch approved these changes

2024-04-26 11:34 UTC, Asiderr commented on content/faq-shop.md
> +###### Q: You are shipping Full PC Builds. How can I be sure that my package will arrive intact?
```suggestion
#### Q: How can I be sure that my Full PC Builds will arrive intact?
```

2024-04-29 08:35 UTC, Stanislaw-bnk commented on content/faq-shop.md
> +###### Q: You are shipping Full PC Builds. How can I be sure that my package will arrive intact?
fixed 89bc631ab03119b39ea846ce3618e05642bc051d

2024-04-29 08:35 UTC, Stanislaw-bnk commented on content/faq-shop.md
> +###### Q: I value what you are doing and would like to support you. How can I do this?
fixed 89bc631ab03119b39ea846ce3618e05642bc051d

2024-04-29 08:48 UTC, Asiderr requested changes

2024-04-29 08:48 UTC, Asiderr commented on themes/3mdeb/layouts/_default/sitemap.xml
> +                {{ if not (strings.HasSuffix .Permalink "/faq-shop/") }}<url>
Please use `{{- ... -}}` to increase readability.

2024-04-29 08:48 UTC, Asiderr commented on themes/3mdeb/layouts/_default/sitemap.xml
> +  </url>{{ end }}{{- end -}}{{ end }}{{- end -}}{{ end }}{{- end -}}{{ end }}{{ end }}
Please use {{- ... -}} to increase readability.

2024-04-29 09:16 UTC, Stanislaw-bnk commented on themes/3mdeb/layouts/_default/sitemap.xml
> +                {{ if not (strings.HasSuffix .Permalink "/faq-shop/") }}<url>
@Asiderr fixed 22ab76594681ff94d5cb8a5c691ffda0194d109d

2024-04-29 09:16 UTC, Stanislaw-bnk commented on themes/3mdeb/layouts/_default/sitemap.xml
> +  </url>{{ end }}{{- end -}}{{ end }}{{- end -}}{{ end }}{{- end -}}{{ end }}{{ end }}
@Asiderr fixed 22ab76594681ff94d5cb8a5c691ffda0194d109d

2024-04-29 09:18 UTC, Asiderr approved these changes

2024-04-30 07:17 UTC, merged