logo-policy.md: delete information about eu fundings
3mdeb/3mdeb-website pull request #170
Opened 2024-09-24 11:48 UTC by Stanislaw-bnk

2024-09-26 15:15 UTC, artur-rs requested changes

2024-09-26 15:15 UTC, artur-rs commented on content/_index.md
> +  clients_image: ""
@Stanislaw-bnk, if you removed this line, shouldn't you also remove the source file for this jpg? I used `grep` on the root folder, and I do not see any more calls to this file.

2024-09-27 10:58 UTC, Stanislaw-bnk commented on content/_index.md
> +  clients_image: ""
@artur-rs Done 5b0e41cdb6592f4b128f5f9d6a53f9d3448bdf73

2024-09-27 12:22 UTC, artur-rs approved these changes

2024-09-27 12:22 UTC, merged